from __future__ import annotations

from decimal import Decimal
from typing import Protocol

from navabe_api.domain.models import Admin, Book, Order, OrderLine, User


class NavabeRepository(Protocol):
    def list_books(self, query: str, limit: int, offset: int, sort: str, direction: str) -> list[Book]: ...
    def count_books(self, query: str) -> int: ...
    def get_book(self, isbn: str) -> Book | None: ...
    def stock_available(self, isbn: str, quantity: int) -> bool: ...
    def create_user(self, name: str, first_name: str, address: str, email: str, password_hash: str) -> User: ...
    def get_user_by_email(self, email: str) -> tuple[User, str] | None: ...
    def get_user_by_id(self, identifier: str) -> tuple[User, str] | None: ...
    def update_user_password(self, identifier: str, password_hash: str) -> bool: ...
    def create_order(self, user_id: str, transaction_id: str, lines: tuple[OrderLine, ...], amount: Decimal) -> Order: ...
    def get_admin_by_id(self, identifier: str) -> tuple[Admin, str] | None: ...
    def create_admin(self, name: str, first_name: str, email: str, password_hash: str) -> Admin: ...
    def update_admin_password(self, identifier: str, password_hash: str) -> bool: ...
    def upsert_book(self, book: Book, quantity: int) -> Book: ...
    def delete_book(self, isbn: str) -> bool: ...
    def get_order(self, identifier: str) -> dict | None: ...
    def statistics(self, metric: str, group_by: str) -> dict: ...


class Mailer(Protocol):
    def send(self, recipient: str, subject: str, body: str) -> None: ...
